### ISSUE TITLE
Issue with 'ms' steps

### ISSUE THREAD

**Issue by eugenesiow** [streamreasoning/CSPARQL-engine#18]
Hi,

Steps of 'ms' are not working because the parser is looking for '<SINGLELETTERTEXT>' like 's', 'h', 'd' so 'ms' causes a parse exception. The JavaCC grammar for the parser can perhaps be modified slightly to support this.

Cheers!

**Comment by dellaglio** [comment]
Hi,
it is a design choice to do not allow to express windows in "ms". In other words, the minimal time unit is 1s. 
We made several tests and we decided to use seconds as minimal time unit, as it fits the use cases we have in mind and it drastically reduces the cases where the system fails (i.e. when the time to process the data requires more time than the window size).

**Comment by eugenesiow** [comment]
Noted!
I thought that 'ms' was supported based on the Barbieri et al. (2010) SIGMOD Record paper and there was this bit of source in CsparqlParser: 
```java
t = jj_consume_token(SINGLELETTERTEXT);
         timeunit = timeunit + t.image ;
        if(!timeunit.equals("ms") && !timeunit.equals("s") && !timeunit.equals("m") && !timeunit.equals("h") && !timeunit.equals("d"))
                {if (true) throw new ParseException();}
         {if (true) return TimeUnit.getUnitOfMeasure(timeunit);}
```
Thanks for the clarification! It would be a great help for more general use cases and benchmarking if you change your mind and decide to fix this though.
