### ISSUE TITLE
It's not possible to get bindings by var name from RDFTuple

### ISSUE THREAD

**Issue by KMax** [streamreasoning/CSPARQL-engine#2]
I want to convert RDFTuple to [BindingMap](http://jena.apache.org/documentation/javadoc/arq/com/hp/hpl/jena/sparql/engine/binding/BindingMap.html) from Apache Jena, but as I see in [RDFTuple.get(int)](https://github.com/streamreasoning/CSPARQL-engine/blob/b3ef8e7c041e35ca3eb3e1f31f7f755161efa280/csparql-common/src/main/java/eu/larkc/csparql/common/RDFTuple.java#L53) method I can get only first two values and then the method returns `null`. Of course I can call RDFTuple.toString(), but why?

**Comment by mbalduini** [comment]
Dear Maxim, first of all thank you very much for using the C-SPARQL engine. 
The results of a continuous C-SPARQL Query is a RDFTable, that is an extension of a Collections<RDFTuple>. The RDFTuple contains a single row of the result o a query. 
For a SELECT query a single RDFTuple contains the value of the projected variables, for a COSTRUCT query a single RDFTuple contains a triple of the result graph.
Thanks to your message, we found and corrected an error in the RDFTuple class that forces the class to return null for the variable in the position > 2.
You can find the corrected version in the new release (0.9.5.1).
Thank you again.
Marco

**Comment by KMax** [comment]
Thanks @mbalduini!

I just wanted to switch to this new version (`0.9.5.1`), but I've found that it wasn't published on [the maven repo](http://streamreasoning.org/maven/eu/larkc/csparql/csparql-core/). Could you please also publish the new version on the repo?
