### ISSUE TITLE
Need Help plz

### ISSUE THREAD

**Issue by skyboys22** [streamreasoning/CSPARQL-engine#24]
Hello,

I cloned the projet but i didn't knew how to launch the project, no information is figured in readme or wiki.
can you tell me how to launch the application?

by mail to medi_dev@outlook.com or here 

thank you in advance

best regards

**Comment by skyboys22** [comment]
I have the same problem any answer or help plz !

**Comment by skyboys22** [comment]
No answers ! i need help plz

**Comment by mbalduini** [comment]
Please refer to [1] and [2] for the ready to go pack.

[1] https://github.com/streamreasoning/CSPARQL-ReadyToGoPack
[2] http://streamreasoning.org/resources/c-sparql
