### ISSUE TITLE
How extract the value from a literal object?

### ISSUE THREAD

**Issue by dellaglio** [streamreasoning/CSPARQL-engine#7]
I am writing a formatter, and I would like to extract the actual value from a literal object, e.g., if I have "2"^^xsd:int, I want to get 2. At the moment, I solved with this code:
```
Iterator it = ((RDFTable)arg).getTuples().iterator();
while(it.hasNext){
  RDFTuple t = it.next()
  System.out.println(Integer.parseInt(t.get(0).split("\"")[1]));
}
```
Apparently, RDFTuple has only a method get() that returns a String. Is there another way to get the value?

**Comment by mbalduini** [comment]
Internal methods of Csparql engine use String as main datatype.
The RDF tuple contains String as fields.
