### ISSUE TITLE
Federated query

### ISSUE THREAD

**Issue by garayzuev** [streamreasoning/CSPARQL-engine#8]
How can I write a federated query using C-SPARQL to endpoint with authorization? For example, I want to get static data from Fuseki, which has authorization and I use next query
```
REGISTER QUERY test AS 
CONSTRUCT { ?x ?y ?z; ?q ?w. }
FROM STREAM <http://ex.org/streams/test> [RANGE 1m STEP 1m]  
WHERE { 
  ?x ?y ?z.
  SERVICE <${address_to_fuseki}>{
  ?x ?q ?w.
  }
}
```

**Comment by mbalduini** [comment]
The C-SPARQL engine is based on Jena and the SERVICE clause is completely managed by Jena framework. To the best of my knowledge there is no way to perform authentication directly in a SPARQL/C-SPARQL query and the actual version of C-SPARQL Engine does not support federated queries with authentication.

**Comment by garayzuev** [comment]
Thanks for you answer!
